name: instagram_ui

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/instagram_ui/**"
      - ".github/workflows/instagram_ui.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      coverage_excludes: "**/*.g.dart"
      flutter_channel: stable
      flutter_version: 3.16.9
      working_directory: packages/instagram_ui
      min_coverage: 0
      analyze_directories: lib gallery test
      format_directories: lib gallery test
